# Generated by Django 5.0.6 on 2024-06-20 02:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('try', '0002_jurisdiction_remove_game_image_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='jurisdiction',
            name='game',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='try.game'),
            preserve_default=False,
        ),
    ]
