# Generated by Django 5.0.6 on 2024-06-20 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('try', '0003_jurisdiction_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='link',
            field=models.URLField(null=True),
        ),
    ]
