# Generated by Django 5.0.6 on 2024-06-20 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('try', '0004_alter_game_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
